### ISSUE TITLE
R代码段的语法

### ISSUE THREAD

**Issue by yihui** [cloudly/Play-Econometrics-with-R#3]
第一件事就是要修正某些代码段的语法，应该是三个反引号加空格加大括号，你有好些代码段中反引号与`{r}`之间没有空格。应该是这样的：

``````
``` {r foo, eval=TRUE, echo=FALSE, ...}
``````

**Comment by cloudly** [comment]
嗯啊....其实我一直不知道正确的格式是啥，参数可以配哪些，哈哈……偷懒啊偷懒

**Comment by cloudly** [comment]
看到一堆warnings...很多函数都已经更新换代了啊，哎～ 得与时俱进了。

**Comment by yihui** [comment]
在用中学：http://yihui.name/knitr/options

**Comment by yihui** [comment]
用最新版本的话，这个就不成问题了，我已经去掉了空格的限制，但还是推荐你空格，原因是这样的话源文档的代码也能在Github上正确显示。
