### ISSUE TITLE
quantile这节让詹鹏添加上就好

### ISSUE THREAD

**Issue by joegaotao** [cloudly/Play-Econometrics-with-R#5]
quantile这节要詹鹏添加上呗http://www.xiaowanxue.com/up_files/2012121819040.html
这样小册子就可以有增加一部分了。

如果是两年前，我就帮丽云姐把时序的都写了。。。但是现在就还是等有时间吧。。

**Comment by cloudly** [comment]
我现在想的是，谁要写就另起炉灶吧，这个册子等我慢慢酝酿一下重写好了...宁缺勿滥..

2013/10/26 Gao Tao notifications@github.com

> quantile这节要詹鹏添加上呗http://www.xiaowanxue.com/up_files/2012121819040.html
> 这样小册子就可以有增加一部分了。
> 
> 如果是两年前，我就帮丽云姐把时序的都写了。。。但是现在就还是等有时间吧。。
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cloudly/Play-Econometrics-with-R/issues/5
> .

## 

Find me at www.cloudlychen.net

Marketing Analyst
China Analytics Center (Shanghai), eBay.

**Comment by joegaotao** [comment]
。。憋大招啊..不过是需要重写下其实。内容如果能从涵盖初级、中高级计量基本就可以了...现在有的英文册子都太简单了。丽云姐继续加油搞起，不过如果不是每天继续点，很容易就放下了...

**Comment by cloudly** [comment]
关键是现在我觉得计量不怎么重要了...这东西技术上也就那么回事儿...还是直觉和思想更重要些，实验设计最关键。技术上更好玩的东西有的是...

好吧我默默的闪了。最近没有写东西的想法了，工作上的事儿太多...

On Saturday, October 26, 2013, Gao Tao wrote:

> 。。憋大招啊..不过是需要重写下其实。内容如果能从涵盖初级、中高级计量基本就可以了...现在有的英文册子都太简单了。丽云姐继续加油搞起，不过如果不是每天继续点，很容易就放下了...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cloudly/Play-Econometrics-with-R/issues/5#issuecomment-27147861
> .

## 

Find me at www.cloudlychen.net

Marketing Analyst
China Analytics Center (Shanghai), eBay.

**Comment by yihui** [comment]
主心骨失去了兴趣，那只能发掘下一个有强烈兴趣的人了，最好是在校的，不然工作之后一回头都像丽云这样看破红尘了 :hear_no_evil:

**Comment by eclee** [comment]
啊！那我可以毛遂自荐承接此工作？我叫 李宜熹，是台湾同胞。台湾中山大学财务管理博士，另在中南大学进修管理科学博士。前年，因为因缘际会，我有向 COS 的魏太云请教了 Optimization 套件的问题，深感 COS 的夥伴对于 R 软体有无限的热忱与能力，而且又非常热于助人～
目前我是台湾 R 使用者社群 (https://www.youtube.com/user/TWuseRGroup) 的一员～最近，买了 Xie 老大的一本新书拜读中 (Dynamic Documents with R and knitr)。

**Comment by yihui** [comment]
@eclee 那当然好啊，我们求之不得！！

**Comment by eclee** [comment]
很高兴能加入各位的行列，看看有没有什么要指派我做的～

也许下次 COS 的年会，台湾的同胞也能组一团加入你们的大家庭～若有机会更期待能邀请你们来台湾推广 R~

最后，Xie 大大，最近我发现预先在 R 执行 Sys.setlocale(category = "LC_ALL", locale = "C") 这行指令，可以解决许多动态文件不支援中文的问题，例如：sldify。最后，动态文件编译完成后再透过 Sys.setlocale(category = "LC_ALL", locale = "") 可以将编码转回原来的状态 (后者为选择性，若显示有问题再转回，否则则没有转回必要)。对此，提出供 您参考～

**Comment by joegaotao** [comment]
@eclee 李宜熹你好啊！原来还是校友~~我是魏太云师弟高涛，也是中南毕业的。你想如何承接这个工作，需要其他人一起加入帮助你完善么？我这边还有人选~

**Comment by yihui** [comment]
书稿的事情你可以和高涛一伙人一起折腾。

关于你的`Sys.setlocale()`建议，我想我现在对编码的理解已经可以解决这个问题了。设置locale为C有一些副作用（例如对字符排序有影响），中文问题最好还是通过encoding参数来解决，例如`knit(..., encoding='BIG5')`（如果你确定文档是BIG5编码的）。

**Comment by eclee** [comment]
Dear All:
很荣幸加入团队。 
@joegaotao 高兄：很高兴认识你，魏师兄近来可好？
关于这份工作的延续，容我详阅 @cloudly  与夥伴们先前完成的内容，于 11/20 提出初步想法向大家请益未来承接方向，这份工作是一定要大家共同参与的~
@yihui 谢兄：我真是太喜欢你开发的knitr套件与书籍了！前一星期，我都抱著你的书睡觉 (随身在侧)！

**Comment by yihui** [comment]
受宠若惊：）

**Comment by eclee** [comment]
啊，抱歉，近期连换了三台笔电 (有点凄惨），搜了一会儿才找到这里的连结～

先前，我看过 原版主的写作理念，非常棒！对此，我提两类走法，向大家请教～
1. 由资料 (实例) 出发玩计量 (原此书的理念)：
   由做中学，是一件非常高竿的写作与教学策略，但要找的精致的资料 (实例) 是非常辛苦的！近期，Gujarati 的新计量书籍 Econometrics by Example (http://www.amazon.com/Econometrics-Example-Damodar-Gujarati/dp/0230290396) 正导引完全朝此方向迈进。而 Wooldridge 的 Introductory Econometrics: A Modern Approach 应该是此类别写作一直以来的计量经典～
2. 由计量理论出发，伴随实例玩资料：
   这方面的原文经典书籍很多，常见的是 Hill et al. Principle of Econometrics (搭配软体 EViews, Stata, Excel, SAS, GRETL...etc.) [http://principlesofeconometrics.com/poe4/poe4.htm]，Kleiber 出版的 Applied Econometrics with R (搭配 R 的 AER 包)，内地出版的 陈灯塔 应用经济计量学 (搭配软体：EViews) ＆ 陈强 高级计量经济学及 Stata 应用 (搭配软体： Stata)。

对于不同的走法，不知道大家有没有什么想法？

**Comment by yihui** [comment]
@eclee 我倾向于以实例出发。显然我们这些人里面没有合适担任带头组织工作的，不然也不会没有人接着回复 :smile:
